# Generated by Django 5.2.1 on 2025-06-07 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0005_alter_demandeenchaire_state'),
        ('notification', '0002_notificationdemandeenchaire_enchaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdemandeenchaire',
            name='enchaire',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_demande', to='Ezayd.enchaire'),
        ),
        migrations.AlterField(
            model_name='notificationdemandeenchaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_demande', to=settings.AUTH_USER_MODEL),
        ),
    ]
