# Generated by Django 5.2.2 on 2025-06-06 02:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BijouxObjetValeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=50)),
                ('poids', models.FloatField(help_text='Poids en grammes')),
                ('carats', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Immobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('type_bien', models.CharField(choices=[('habitation', 'Habitations'), ('locaux_commerciaux', 'Locaux commerciaux'), ('terrain', 'Terrains')], max_length=30)),
                ('surface', models.FloatField(help_text='Surface en m²')),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=50)),
                ('code_postal', models.CharField(max_length=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('nombre_pieces', models.IntegerField(blank=True, null=True)),
                ('nombre_chambres', models.IntegerField(blank=True, null=True)),
                ('salle_de_bain', models.IntegerField(blank=True, null=True)),
                ('garage', models.BooleanField(default=False)),
                ('jardin', models.BooleanField(default=False)),
                ('piscine', models.BooleanField(default=False)),
                ('date_construction', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformatiqueElectronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(choices=[('ordinateur', 'Ordinateur'), ('telephone', 'Téléphone'), ('tv_audio', 'TV / Audio'), ('autre', 'Autre')], max_length=30)),
                ('marque', models.CharField(blank=True, max_length=50, null=True)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('etat', models.CharField(blank=True, max_length=100, null=True)),
                ('garantie', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('vehicules', 'Véhicules'), ('immobilier', 'Immobilier'), ('materiel_pro', 'Matériel professionnel'), ('informatique_electronique', 'Informatique & électronique'), ('mobilier_equipements', 'Mobilier & équipements'), ('bijoux_objets_valeur', 'Bijoux & objets de valeur'), ('stocks_invendus', 'Stocks et invendus'), ('oeuvres_collections', 'Œuvres & collections')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BijouxImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bijoux/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='photo', max_length=30)),
                ('bijou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Ezayd.bijouxobjetvaleur')),
            ],
        ),
        migrations.CreateModel(
            name='Enchaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(default=django.utils.timezone.now)),
                ('first_price', models.IntegerField()),
                ('pas', models.IntegerField()),
                ('text_highlight', models.TextField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('upcoming', 'À venir'), ('active', 'En cours'), ('finis', 'Terminé')], default='upcoming', max_length=10)),
                ('is_reserved', models.BooleanField(default=False)),
                ('price_reserved', models.IntegerField(blank=True, null=True)),
                ('notified_users', models.ManyToManyField(blank=True, related_name='enchaires_notifiées', to=settings.AUTH_USER_MODEL)),
                ('savers', models.ManyToManyField(blank=True, related_name='enchaires_saved', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enchaires_proprietes', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enchères_gagnées', to=settings.AUTH_USER_MODEL)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enchaire', to='Ezayd.lot')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeEnchaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_enchere', to=settings.AUTH_USER_MODEL)),
                ('enchaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande', to='Ezayd.enchaire')),
            ],
        ),
        migrations.CreateModel(
            name='ImmobilierImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='immobilier/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('1', 'main_image'), ('2', 'interior_image'), ('3', 'exterior_image'), ('4', 'floor_plan'), ('5', 'additional_image')], default='5', max_length=20)),
                ('immobilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Ezayd.immobilier')),
            ],
        ),
        migrations.CreateModel(
            name='InformatiqueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='informatique/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='photo', max_length=30)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Ezayd.informatiqueelectronique')),
            ],
        ),
        migrations.AddField(
            model_name='informatiqueelectronique',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informatique', to='Ezayd.lot'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobiliers', to='Ezayd.lot'),
        ),
        migrations.AddField(
            model_name='bijouxobjetvaleur',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bijoux', to='Ezayd.lot'),
        ),
        migrations.CreateModel(
            name='MaterielProfessionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_materiel', models.CharField(choices=[('machines_equipements', 'Machines & équipements'), ('engins_chantier', 'Engins de chantier'), ('materiel_agricole', 'Matériel agricole')], max_length=30)),
                ('marque', models.CharField(blank=True, max_length=50, null=True)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('annee_fabrication', models.IntegerField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, max_length=100, null=True)),
                ('puissance', models.CharField(blank=True, max_length=50, null=True)),
                ('poids', models.FloatField(blank=True, help_text='Poids en kg', null=True)),
                ('description', models.TextField()),
                ('disponibilite', models.BooleanField(default=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='Ezayd.lot')),
            ],
        ),
        migrations.CreateModel(
            name='MaterielProfessionnelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='materiel_pro/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('1', 'main_image'), ('2', 'detail_image'), ('3', 'usage_image'), ('4', 'technical_sheet'), ('5', 'additional_image')], default='5', max_length=20)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Ezayd.materielprofessionnel')),
            ],
        ),
        migrations.CreateModel(
            name='MobilierEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
                ('materiau', models.CharField(blank=True, max_length=50, null=True)),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('etat', models.CharField(blank=True, max_length=100, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilier', to='Ezayd.lot')),
            ],
        ),
        migrations.CreateModel(
            name='MobilierImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mobilier/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='photo', max_length=30)),
                ('mobilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Ezayd.mobilierequipement')),
            ],
        ),
        migrations.CreateModel(
            name='OeuvreCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('artiste', models.CharField(blank=True, max_length=100, null=True)),
                ('annee_creation', models.IntegerField(blank=True, null=True)),
                ('type_oeuvre', models.CharField(max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('technique', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oeuvres', to='Ezayd.lot')),
            ],
        ),
        migrations.CreateModel(
            name='OeuvreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='oeuvres/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='photo', max_length=30)),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Ezayd.oeuvrecollection')),
            ],
        ),
        migrations.CreateModel(
            name='StockInvendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('unite', models.CharField(default='pièces', max_length=20)),
                ('description', models.TextField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='Ezayd.lot')),
            ],
        ),
        migrations.CreateModel(
            name='StockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stocks/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='photo', max_length=30)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Ezayd.stockinvendu')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=2025)),
                ('numero_chassis', models.CharField(max_length=20, null=True)),
                ('etat', models.IntegerField(null=True)),
                ('couleur', models.CharField(max_length=20, null=True)),
                ('details', models.TextField()),
                ('youtube_video', models.URLField(blank=True, null=True)),
                ('climatiseur', models.BooleanField(default=False)),
                ('gps_navigation', models.BooleanField(default=False)),
                ('toit_ouvrant', models.BooleanField(default=False)),
                ('sieges_ventiles', models.BooleanField(default=False)),
                ('camera_recul', models.BooleanField(default=False)),
                ('capteurs_stationnement', models.BooleanField(default=False)),
                ('regulateur_vitesse', models.BooleanField(default=False)),
                ('regulateur_vitesse_adaptatif', models.BooleanField(default=False)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='Ezayd.lot')),
            ],
        ),
        migrations.CreateModel(
            name='VoitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('1', 'main_image'), ('2', 'side_image'), ('3', 'inside_image'), ('4', 'engine_image'), ('5', 'additional_image'), ('6', 'main_side_image'), ('7', 'main_inside_image'), ('8', 'main_engine_image'), ('9', 'registrations_paper_image')], default='5', max_length=20)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Ezayd.voiture')),
            ],
        ),
        migrations.AddIndex(
            model_name='enchaire',
            index=models.Index(fields=['etat'], name='Ezayd_encha_etat_c4439e_idx'),
        ),
        migrations.AddIndex(
            model_name='enchaire',
            index=models.Index(fields=['date_debut', 'date_fin'], name='Ezayd_encha_date_de_84d57b_idx'),
        ),
    ]
