# Generated by Django 5.2.2 on 2025-06-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immobilier',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='stockinvendu',
            name='prix_unitaire',
        ),
    ]
