# Generated by Django 5.2.1 on 2025-06-03 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enchaire',
            name='approved',
        ),
        migrations.AlterField(
            model_name='demandeenchaire',
            name='enchaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande', to='Ezayd.enchaire'),
        ),
    ]
