# Generated by Django 5.2.2 on 2025-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0002_remove_immobilier_prix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeenchaire',
            name='date_accepte',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
