# Generated by Django 5.2.2 on 2025-06-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0003_alter_demandeenchaire_date_accepte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeenchaire',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='demandeenchaire',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='demandeenchaire',
            name='seen',
        ),
        migrations.AddField(
            model_name='demandeenchaire',
            name='state',
            field=models.CharField(choices=[('unread', 'Non lu'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='unread', max_length=10),
        ),
    ]
