# Generated by Django 5.2.1 on 2025-06-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0005_alter_demandeenchaire_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='enchaireobjet',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
