# Generated by Django 5.2.2 on 2025-06-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0006_enchaireobjet_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationenchaire',
            name='montant',
        ),
    ]
