# Generated by Django 5.2.2 on 2025-06-08 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0007_remove_participationenchaire_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationenchaire',
            name='montant',
            field=models.IntegerField(default=0, help_text='Montant de la participation', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
