# Generated by Django 5.2.1 on 2025-06-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0008_participationenchaire_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationenchaire',
            name='date_participation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
