# Generated by Django 5.2.2 on 2025-06-09 21:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0009_alter_participationenchaire_date_participation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enchaireobjet',
            name='objet_id',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='enchaireobjet',
            name='type',
            field=models.CharField(choices=[('vehicules', 'Véhicules'), ('immobilier', 'Immobilier'), ('materiel_pro', 'Matériel professionnel'), ('informatique_electronique', 'Informatique & électronique'), ('mobilier_equipements', 'Mobilier & équipements'), ('bijoux_objets_valeur', 'Bijoux & objets de valeur'), ('stocks_invendus', 'Stocks et invendus'), ('oeuvres_collections', 'Œuvres & collections')], default='vehicules', max_length=30),
        ),
        migrations.AlterField(
            model_name='participationenchaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_encheres', to=settings.AUTH_USER_MODEL),
        ),
    ]
