# Generated by Django 5.2.2 on 2025-06-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0011_alter_enchaireobjet_objet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enchaireobjet',
            name='objet_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='enchaireobjet',
            name='type',
            field=models.CharField(blank=True, choices=[(None, '-'), ('vehicules', 'Véhicules'), ('immobilier', 'Immobilier'), ('materiel_pro', 'Matériel professionnel'), ('informatique_electronique', 'Informatique & électronique'), ('mobilier_equipements', 'Mobilier & équipements'), ('bijoux_objets_valeur', 'Bijoux & objets de valeur'), ('stocks_invendus', 'Stocks et invendus'), ('oeuvres_collections', 'Œuvres & collections')], default=None, max_length=30, null=True),
        ),
    ]
