# Generated by Django 5.2.2 on 2025-06-11 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0014_enchaire_wilaya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enchaire',
            name='text_highlight',
        ),
    ]
