# Generated by Django 5.2.1 on 2025-06-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0015_remove_enchaire_text_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
