# Generated by Django 5.2.1 on 2025-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0016_alter_lot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
