# Generated by Django 5.2.1 on 2025-06-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ezayd', '0017_alter_lot_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enchaire',
            name='notified_users',
        ),
    ]
